name: Make ZIP and release (Windows)

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag'
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: git clone
      run: |
        git clone https://${{ secrets.MURGI }}@github.com/mcpebd/mtrls.git

    - name: Make ZIP
      run: |
        pushd 'mtrls/windows' ; zip -r ../../materials_windows.zip * -x "*.git*" ".github/*" ".gitignore" ; popd

    - name: Upload to release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release create ${{ github.event.inputs.release_tag }} materials_windows.zip --title "${{ github.event.inputs.release_tag }}" --notes "${{ github.event.inputs.release_tag }} $(date +'%Y%m%d')" --latest
